development:
  adapter: postgresql
  encoding: unicode
  database: sealand_dev
  pool: 5
  username: sealand
  password: sealand

test:
  adapter: postgresql
  encoding: unicode
  database: sealand_test
  pool: 5
  username: sealand
  password: sealand
